services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skeleton_g9
    image: skeleton_g9
    ports: 
      - "8098:8000"
    # environment:
    #   PGCONTAINER_NAME: ${PGCONTAINER_NAME}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   DEPLOYMENT_MODE: local